### ISSUE TITLE
Dask Lab-extension not connecting with dask-gateway dashboards

### ISSUE THREAD

**Issue by viniciusdc** [dask/dask-labextension#225]
This is a cross-post of https://github.com/Quansight/qhub/issues/1012

## What happened:

I pasted a link to a dask gateway cluster dashboard into the dask lab extension search box, and nothing happened. 

What you expected to happen:

The behavior should be the same one as we can see for `dask.distributed` dashboard links (which does work), e.g. allowing me to open the various windows of the dashboard in Jupiter lab.

## Minimal Complete Verifiable Example:

From jupyterlab
```python
from dask_gateway import Gateway
gateway = Gateway()
cluster = gateway.new_cluster()
```
Then I copy/paste the dashboard link, into the lab extension. Nothing happens. The lab extension never becomes active.

![image](https://user-images.githubusercontent.com/51954708/157269269-1f094d9f-538b-4875-94c8-b29bba758495.png)

## Anything else we need to know?:

This works for `dask.distributed` dashboards.

This is the related response from the DaskDashboardCheckHandler:

`{"url": "https://quansight.qhub.dev/gateway/clusters/dev.d9667a0ca58f4144a68b920838e01650/", "isActive": false, "plots": {}}`

Also, the dashboard is available and we can easily connect to it by the same URI
![image](https://user-images.githubusercontent.com/51954708/157269870-6f565bb9-a65d-4412-bde4-f0e37d616bd7.png)

Kernel Environment:
```yaml
  "environment-dask.yaml":
    name: dask
    channels:
      - conda-forge
    dependencies:
      - python
      - ipykernel
      - ipywidgets
      - python-graphviz
      - dask ==2.30.0
      - distributed ==2.30.1
      - dask-gateway ==0.9.0
      - numpy
      - numba
      - pandas
```
A complete environment for the Jupyterlab configuration can be found [here](https://github.com/Quansight/qhub/blob/main/qhub/template/image/jupyterlab/environment.yaml)
Python version: 3.8
Operating System: Linux
Install method: Conda
