### ISSUE TITLE
Can only start local clusters and not with SLURM 

### ISSUE THREAD

**Issue by tomtok9** [dask/dask-labextension#78]
We are currently trying to run dask, jobqueue and labextension on our cluster as a test. We could start a cluster by hand and also with the jobqueue file. 
We cannot start SLURM Cluster with the dask-labextension. It is probably simular issue with this one https://github.com/dask/dask-labextension/issues/68  or it is just a miss configuration. 
We could start the cluster by hand without troubles. When we use the dask-labextension we got the following error:

> Cluster Start Error
> 'LocalCluster' object has no attribute 'scheduler'

It looks like he's trying to start a local cluster, but we've adjusted all labextensions.yaml files we could find. 
~/.config/dask/
we copied also to /etc/dask 
and also in the /usr/local/lib/python3.6/dist-packages/dask_labextension folder.

Does someone have an idea what I'm doing wrong? 

labextension: 
```
labextension:
  factory:
    module: 'dask_jobqueue'
    class: 'SLURMCluster'
    args: []
    kwargs: {'cores': 1,
             'processes': 1,
             'memory': '40GB',
             'interface' : 'ib0',
             'queue': 'gpu',
             'walltime': '0:30:00',
             'project': 'gpu'}
  default:
    workers: null
    adapt:
      null
      # minimum: 0
      # maximum: 10
  initial:
    []
    # - name: "My Big Cluster"
    #   workers: 100
    # - name: "Adaptive Cluster"
    #   adapt:
    #     minimum: 0
    #     maximum: 50
```

pip list : 
```
dask (2.2.0+12.gb5722b36)
dask-jobqueue (0.6.2)
dask-labextension (1.0.3)
```

jupyter serverextension list:

```
config dir: /usr/etc/jupyter
    dask_labextension  enabled 
    - Validating...
      dask_labextension 1.0.3 OK
config dir: /usr/local/etc/jupyter
    dask_labextension  enabled 
    - Validating...
      dask_labextension 1.0.3 OK
    ipyparallel.nbextension  enabled 
    - Validating...
      ipyparallel.nbextension  OK
    jupyter_server_proxy  enabled 
    - Validating...
      jupyter_server_proxy  OK
    jupyterlab  enabled 
    - Validating...
      jupyterlab 1.0.4 OK
```

**Comment by ian-r-rose** [comment]
Thanks for the report @tomtok9. What version of `distributed` are you using? @mrocklin Could this have anything to do with #73?

**Comment by ian-r-rose** [comment]
Also, can you inspect the config object manually, @tomtok9, to see if `dask` is picking up the right config files? (`dask.config.get`)

**Comment by mrocklin** [comment]
This is being resolved in https://github.com/dask/dask-jobqueue/pull/307 .
If you can hold off on your experimentation for a few weeks then I
recommend doing so.

**Comment by mrocklin** [comment]
Actually, I suspect that your problem would be solved if you just updated to the git-master development version of dask-labextension

**Comment by mrocklin** [comment]
I think that this was fixed by https://github.com/dask/dask-labextension/pull/73

**Comment by adavanisanti** [comment]
Hi @mrocklin,

I am trying to start a slurm cluster but I see the same problem `'LocalCluster' object has no attribute 'scheduler'`.

I installed dask-labextension from the latest git master. Could you let me know if I am missing something?

Appreciate your help!

Thanks
Santi

My installations are as follows:
```
dask                   2.4.0
dask-jobqueue          0.6.3
dask-labextension      1.0.3                       /home/ubuntu/dask-labextension
distributed            2.4.0
```

labextension.yaml
```
labextension:
  factory:
    module: 'dask_jobqueue'
    class: 'SLURMCluster'
    args: []
    kwargs: {}
  default:
    workers: null
    adapt: null
      # minimum: 0
      # maximum: 10
  initial: []
```

slurm part of jobqueue.yaml

```
slurm:
    name: dask-worker

    # Dask worker options
    cores: 2                 # Total number of cores per job
    memory: 2                # Total amount of memory per job
    processes: 1                # Number of Python processes per job

    interface: null             # Network interface to use like eth0 or ib0
    death-timeout: 60           # Number of seconds to wait if a worker can not find a scheduler
    local-directory: null       # Location of fast local storage like /scratch or $TMPDIR
```

jupyter server extension:

```
config dir: /opt/conda/etc/jupyter
    jupyter_server_proxy  enabled
    - Validating...
      jupyter_server_proxy  OK
    jupyterlab  enabled
    - Validating...
      jupyterlab 1.1.3 OK
    dask_labextension  enabled
    - Validating...
      dask_labextension 1.0.3 OK
```
